[access_scopes]
scopes = "read_products,write_products,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://launchguard.sample-guard.com/auth/callback"
]

[app_proxy]
url = "https://launchguard.sample-guard.com/apps/launchguard"
subpath = "launchguard"
prefix = "apps"

[pos]
embedded = false
