api_version = "2026-04"
uid = "fba1f6fa-e31c-c2c6-7a7e-5d923262c44fc46d48ce"

[[extensions]]
type = "function"
name = "LaunchGuard Purchase Limit Validator"
handle = "launchguard-checkout-validation"
description = "Validates cart quantities against active LaunchGuard campaign limits."

[extensions.build]
command = "npm run build"
path = "dist/index.wasm"
